# =============================================================================
# EnerSense — ml/train.py
# Trains a Ridge regression model to predict next-hour energy consumption.
#
# Features:
#   - hour_sin, hour_cos   : cyclic encoding of hour of day
#   - day_of_week          : 0 (Monday) – 6 (Sunday)
#   - lag_1h, lag_2h, lag_3h : energy consumed in the previous 1/2/3 hours
#
# Target:
#   - energy_next_1h (kWh) : energy that will be consumed in the next hour
#
# Usage:
#   python ml/train.py                        # pulls data from InfluxDB
#   python ml/train.py --csv data/sample.csv  # use a CSV file instead
#
# Output:
#   ml/model.joblib      trained model
#   ml/scaler.joblib     fitted StandardScaler
#   ml/metrics.json      MAE, RMSE, R² on validation set
# =============================================================================

import argparse
import json
import math
import os
import sys
import warnings

import numpy as np
import pandas as pd
import joblib

from sklearn.linear_model    import Ridge
from sklearn.preprocessing   import StandardScaler
from sklearn.pipeline        import Pipeline
from sklearn.metrics         import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import TimeSeriesSplit

warnings.filterwarnings('ignore')

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH  = os.path.join(SCRIPT_DIR, 'model.joblib')
SCALER_PATH = os.path.join(SCRIPT_DIR, 'scaler.joblib')
METRICS_PATH = os.path.join(SCRIPT_DIR, 'metrics.json')

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_from_sqlite(db_path=None, node='node_01', appliance='appliance_01'):
    """
    Query the local SQLite database for hourly averaged telemetry.
    Returns a DataFrame with columns: timestamp (index), P_W, E_Wh.
    """
    import sqlite3

    if db_path is None:
        db_path = os.path.normpath(os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            '..', 'server', 'enersense.db'
        ))

    if not os.path.exists(db_path):
        print(f"[Train] ERROR: SQLite DB not found at {db_path}")
        print("        Start database.py first or use --synthetic.")
        sys.exit(1)

    print(f"[Train] Loading from SQLite: {db_path}")
    conn = sqlite3.connect(db_path)
    query = """
        SELECT (ts / 3600000) * 3600000 AS timestamp_h,
               AVG(P_W) AS P_W, MAX(E_Wh) AS E_Wh
        FROM telemetry
        WHERE node = ? AND appliance = ?
        GROUP BY timestamp_h ORDER BY timestamp_h ASC
    """
    df = pd.read_sql_query(query, conn, params=(node, appliance))
    conn.close()

    if df.empty:
        print("[Train] ERROR: No data in database. Use --synthetic to test.")
        sys.exit(1)

    df['timestamp'] = pd.to_datetime(df['timestamp_h'], unit='ms')
    df.set_index('timestamp', inplace=True)
    df = df[['P_W', 'E_Wh']].astype(float)
    print(f"[Train] Loaded {len(df)} hourly records from SQLite.")
    return df


def load_from_csv(path):
    """
    Load data from a CSV file.
    Expected columns: timestamp (parseable datetime), P_W, E_Wh
    The CSV can be exported from InfluxDB or generated by the sample
    data generator below.
    """
    print(f"[Train] Loading CSV: {path}")
    df = pd.read_csv(path, parse_dates=['timestamp'])
    df.set_index('timestamp', inplace=True)
    df = df[['P_W', 'E_Wh']].astype(float)
    print(f"[Train] Loaded {len(df)} records from CSV.")
    return df


def generate_sample_data(n_hours=336):
    """
    Generate synthetic hourly energy data for testing when no real data
    is available yet (336 hours = 2 weeks).

    Pattern: base load + daytime peak + random noise + occasional spikes.
    """
    print(f"[Train] Generating {n_hours}h of synthetic data for testing...")
    rng = np.random.default_rng(42)

    times = pd.date_range(start='2025-01-01', periods=n_hours, freq='h')
    P_W   = np.zeros(n_hours)

    for i, t in enumerate(times):
        hour = t.hour
        dow  = t.dayofweek

        # Base load (always-on appliances: fridge, router, standby)
        base = 80

        # Morning peak (7–9h)
        if 7 <= hour <= 9:
            base += 600 + rng.normal(0, 60)

        # Evening peak (18–22h)
        if 18 <= hour <= 22:
            base += 900 + rng.normal(0, 90)

        # Weekend afternoon activity
        if dow >= 5 and 13 <= hour <= 17:
            base += 400 + rng.normal(0, 40)

        # Random noise
        base += rng.normal(0, 30)

        # Occasional anomaly spike (1% chance)
        if rng.random() < 0.01:
            base += rng.uniform(1500, 2800)

        P_W[i] = max(base, 10)   # never negative

    # Convert W to kWh (hourly average W = kWh for 1h window)
    E_Wh = np.cumsum(P_W)   # cumulative Wh

    df = pd.DataFrame({'P_W': P_W, 'E_Wh': E_Wh}, index=times)
    df.index.name = 'timestamp'
    return df


# ---------------------------------------------------------------------------
# Feature engineering
# ---------------------------------------------------------------------------

def make_features(df):
    """
    Build the feature matrix X and target vector y from an hourly DataFrame.

    Feature set:
        hour_sin, hour_cos  — cyclic hour encoding
        day_sin, day_cos    — cyclic day-of-week encoding
        lag_1h, lag_2h, lag_3h — previous 1/2/3 hour kWh consumption

    Target:
        energy_next_1h (kWh) = P_W / 1000 of the NEXT row
    """
    df = df.copy()

    # Convert W to kWh per hour
    df['kwh'] = df['P_W'] / 1000.0

    # Cyclic time features
    hour = df.index.hour
    dow  = df.index.dayofweek

    df['hour_sin'] = np.sin(2 * math.pi * hour / 24)
    df['hour_cos'] = np.cos(2 * math.pi * hour / 24)
    df['day_sin']  = np.sin(2 * math.pi * dow  / 7)
    df['day_cos']  = np.cos(2 * math.pi * dow  / 7)

    # Lag features
    df['lag_1h'] = df['kwh'].shift(1)
    df['lag_2h'] = df['kwh'].shift(2)
    df['lag_3h'] = df['kwh'].shift(3)

    # Target: next hour kWh
    df['target'] = df['kwh'].shift(-1)

    # Drop rows with NaN (first 3 and last 1)
    df.dropna(inplace=True)

    feature_cols = ['hour_sin', 'hour_cos', 'day_sin', 'day_cos',
                    'lag_1h', 'lag_2h', 'lag_3h']

    X = df[feature_cols].values
    y = df['target'].values

    return X, y, feature_cols


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train(X, y, feature_cols):
    """
    Train a Ridge regression model using time-series cross-validation.
    Returns the fitted pipeline and validation metrics.
    """
    n = len(X)
    print(f"[Train] Dataset: {n} samples, {len(feature_cols)} features")

    # Time-series split — no shuffling to prevent data leakage
    # Use last 20% as held-out test set
    split_idx  = int(n * 0.8)
    X_train, X_test = X[:split_idx], X[split_idx:]
    y_train, y_test = y[:split_idx], y[split_idx:]

    print(f"[Train] Train: {len(X_train)} samples  |  Test: {len(X_test)} samples")

    # Pipeline: StandardScaler → Ridge
    # Ridge alpha=1.0 provides mild L2 regularisation — good generalisation
    # on limited data without over-smoothing.
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('model',  Ridge(alpha=1.0))
    ])

    # Cross-validate on training set (3 folds, time-series aware)
    tscv = TimeSeriesSplit(n_splits=3)
    cv_maes = []

    for fold, (tr_idx, val_idx) in enumerate(tscv.split(X_train)):
        xtr, xval = X_train[tr_idx], X_train[val_idx]
        ytr, yval = y_train[tr_idx], y_train[val_idx]

        pipeline.fit(xtr, ytr)
        pred     = pipeline.predict(xval)
        fold_mae = mean_absolute_error(yval, pred)
        cv_maes.append(fold_mae)
        print(f"[Train]   CV fold {fold+1}: MAE = {fold_mae:.4f} kWh")

    print(f"[Train] Mean CV MAE: {np.mean(cv_maes):.4f} kWh")

    # Final fit on full training set
    pipeline.fit(X_train, y_train)

    # Evaluate on held-out test set
    y_pred = pipeline.predict(X_test)
    mae    = mean_absolute_error(y_test, y_pred)
    rmse   = math.sqrt(mean_squared_error(y_test, y_pred))
    r2     = r2_score(y_test, y_pred)

    print(f"\n[Train] Test set results:")
    print(f"  MAE  = {mae:.4f} kWh")
    print(f"  RMSE = {rmse:.4f} kWh")
    print(f"  R²   = {r2:.4f}")

    metrics = {
        'mae':         round(mae, 6),
        'rmse':        round(rmse, 6),
        'r2':          round(r2, 6),
        'cv_mae_mean': round(float(np.mean(cv_maes)), 6),
        'n_train':     int(len(X_train)),
        'n_test':      int(len(X_test)),
        'features':    feature_cols,
    }

    return pipeline, metrics


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def save(pipeline, metrics):
    joblib.dump(pipeline, MODEL_PATH)
    print(f"[Train] Model saved → {MODEL_PATH}")

    with open(METRICS_PATH, 'w') as f:
        json.dump(metrics, f, indent=2)
    print(f"[Train] Metrics saved → {METRICS_PATH}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='EnerSense model trainer')
    parser.add_argument('--csv',       type=str,  default=None,
                        help='Path to CSV file (timestamp, P_W, E_Wh).')
    parser.add_argument('--synthetic', action='store_true',
                        help='Use synthetic data (no database needed)')
    parser.add_argument('--hours',     type=int,  default=336,
                        help='Hours of synthetic data to generate (default: 336 = 2 weeks)')
    parser.add_argument('--db',        type=str,  default=None,
                        help='Path to SQLite DB (default: server/enersense.db)')
    parser.add_argument('--node',      type=str,  default='node_01')
    parser.add_argument('--appliance', type=str,  default='appliance_01')
    args = parser.parse_args()

    # Load data
    if args.synthetic:
        df = generate_sample_data(n_hours=args.hours)
    elif args.csv:
        df = load_from_csv(args.csv)
    else:
        df = load_from_sqlite(
            db_path=args.db,
            node=args.node,
            appliance=args.appliance
        )

    if len(df) < 10:
        print("[Train] ERROR: Not enough data (need at least 10 hourly records).")
        sys.exit(1)

    # Build features
    X, y, feature_cols = make_features(df)

    # Train
    pipeline, metrics = train(X, y, feature_cols)

    # Save
    save(pipeline, metrics)

    print("\n[Train] Done. Run predict.py to start the inference server.")


if __name__ == '__main__':
    main()